sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -e .
  - pip install -r test-requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install mypy; fi
script:
  - make test
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then make test_mypy; fi
